# Numpy Tutorial

**Sources:**
1. Patrick Loeber [Numpy Crash Course](https://www.youtube.com/watch?v=9JUAPgtkKpI)

In [1]:
import numpy as np
np.__version__

'1.22.4'

### A numpy array (1-Dimensional)

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

#### Shape of an array using `shape` attribute

In [3]:
a.shape

(3,)

#### Datetype of an array using `dtype` attribute

In [4]:
a.dtype

dtype('int32')

#### Dimension of an array using `ndim` attribute

In [5]:
a.ndim

1

#### Size of an array using `size` attribute

In [6]:
a.size

3

#### Size of each element in array using `itemsize` attribute

In [7]:
a.itemsize

4

#### Dot product of an array using `np.dot()` method & `@` sign

<p>It is the sum of the product of 2 arrays.</p>

In [8]:
# Normal way in Python
l1 = [1, 2, 3]
l2 = [4, 5, 6]
list_dot = 0
for i in range(len(l1)):
    list_dot += l1[i] * l2[i]
list_dot

32

In [9]:
# Using np.dot()
a1 = np.array(l1)
a2 = np.array(l2)
array_dot = np.dot(a1, a2)
array_dot

32

Using `@` sign

In [10]:
dot = a1 @ a2
dot

32

### Multidimenstional Arrays

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a.shape

(2, 3)

#### Indexing in multi-dimensional array can be done using ',' comma

In [13]:
print(a[0][1])
print(a[0, 1])
a[0][1] == a[0, 1]

2
2


True

#### Slicing of multi-dimensional arrays can be done by putting commas

`arr[1:3, 2:4]`

-> A 2D array <br>
-> Slice 1st & 2nd row from it <br>
-> And, 2nd & 4th column from it <br>

In [14]:
# If we want all the rows from a specific column
a[:, 1]

array([2, 5])

In [15]:
# If we want all the columns from a specific row
a[1, :]

array([4, 5, 6])

In [16]:
# Last 2 elements of last row
a[-1, -2:]

array([5, 6])

#### Boolean indexing can be done by putting the condition within sqaure brackets

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a>2

array([[False, False,  True],
       [ True,  True,  True]])

In [19]:
a[a>2]

array([3, 4, 5, 6])

#### Using `np.where()` method

In [20]:
np.where(a>2)

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [21]:
# param:
# Condition, filled false values with x, filled true values with y
# Here filling the false values of the respective condition in x,
# and true values with -1
np.where(a>2, a, -1)

array([[-1, -1,  3],
       [ 4,  5,  6]])

In [22]:
# Findind evens
np.where(a%2==0, a, 0)

array([[0, 2, 0],
       [4, 0, 6]])

#### Fancy Indexing

Passing an array of indexes to an array to access it's multiple indexes.

In [23]:
arr = np.array([10, 20, 30, 40, 50, 60])
indexes = [1, 4, 3, 5]

In [24]:
arr[indexes]

array([20, 50, 40, 60])

#### Find indexes of an array where some condition is True, using `np.argwhere()` method

In [25]:
arr2 = np.array([1, 2, 3, 4, 5])

In [26]:
even_indexes = np.argwhere(arr2%2==0)
even_indexes

array([[1],
       [3]], dtype=int64)

In [27]:
even_indexes = even_indexes.flatten()
even_indexes

array([1, 3], dtype=int64)

In [28]:
arr2[even_indexes]

array([2, 4])

#### Transpose of an array using `T` attribute

Shifting all the rows to columns and columns to rows of a matrix.

In [29]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### To get diagonals of an array, we use `np.diag(arr)`

In [30]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.diag(a)

array([1, 5])

In [32]:
np.diag(np.diag(a))

array([[1, 0],
       [0, 5]])

In [33]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Creating an array using `np.arange()` method

In [34]:
# Passing stop value, start=0 (Deafult)
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
# Passing start & stop values
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [36]:
# Passing start, stop & step value
np.arange(5, 10, 2)

array([5, 7, 9])

In [37]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Reshaping an array using `.reshape()` method

The shape should be equal to toal number of values(elements) in the array.

In [38]:
b = a.reshape(2, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
b.shape

(2, 5)

In [43]:
b = b.reshape([5, 2])
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [44]:
b.shape

(5, 2)

In [45]:
a.shape

(10,)

In [46]:
c = a[np.newaxis, :]
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [47]:
# Add new axis to the end of the array
c = a[:, np.newaxis]
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [48]:
c.shape

(10, 1)

#### Concatenating arrays using `np.concatenate()` method

In [54]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a, b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [55]:
# Concatenate another row
c = np.concatenate((a, b), axis=0)  # axis=0 for row, default
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
# Concatenate another column
d = np.concatenate((a, b.T), axis=1) # axis=1 for column
d

array([[1, 2, 5],
       [3, 4, 6]])

In [57]:
# If axis=None, concatenate after flattening them
e = np.concatenate((a, b), axis=None)
e

array([1, 2, 3, 4, 5, 6])

#### Concatenating arrays using `np.hstack()` and `np.vstack()` methods

`np.hstack()` concatenates the array horizontally <br>
`np.vstack()` concatenates the array vertically <br>

In [58]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [59]:
arr3 = np.hstack((arr1, arr2))
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [60]:
arr4 = np.vstack((arr1, arr2))
arr4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### Broadcasting

It is the ability to treat arrays of different shapes arithmetic operations.

In [61]:
arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [62]:
arr1 * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [63]:
arr1 * np.array([2])

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [64]:
arr1 * np.array([[3, 2]])

array([[ 3,  4],
       [ 9,  8],
       [15, 12],
       [21, 16]])

In [65]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
arr1 - 5

array([[-4, -3],
       [-2, -1],
       [ 0,  1],
       [ 2,  3]])

In [67]:
arr1 + 2

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [69]:
arr1 + np.array([[8, 7], [6, 5], [4, 3], [2, 1]])

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [70]:
a

array([[1, 2],
       [3, 4]])

#### Use `.sum()` to calculate the sum of all the values in an array

In [71]:
a.sum()

10

In [72]:
# Rows sum, column sum
a.sum(0), a.sum(axis=1)

(array([4, 6]), array([3, 7]))

#### Use `.mean()` to calculate the mean (average) of all the values in an array

In [73]:
a.mean()

2.5

In [74]:
# Rows mean, column mean
a.mean(0), a.mean(axis=1)

(array([2., 3.]), array([1.5, 3.5]))

##### There are several more methods, we can use them as an instance methods / array methods or numpy methods.

#### Datatypes